In [1]:
import numpy as np 

In [17]:
#dtype to specify data type
a = np.array([1,2,3],dtype='int16')

In [3]:
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [6]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [8]:
#Get dimention
a.ndim

1

In [9]:
b.ndim

2

In [10]:
#Get shape
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [18]:
#Get type
a.dtype

dtype('int16')

In [15]:
b.dtype

dtype('float64')

In [24]:
#Get size in bytes
a.itemsize

2

In [23]:
#Get total size 
a.nbytes

6

In [25]:
#Accessing and changing 


In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,1,13,14]])

In [27]:
#Get specific element [row, col]
a[1,5]

13

In [28]:
#negative notation
a[1,-2]

13

In [29]:
#get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#Get specific col
a[:,2]

array([ 3, 10])

In [31]:
#between 2 elements , every _ num [start index:end index:step size]
a[0,1:6:2]

array([2, 4, 6])

In [32]:
#can also use negative
a[0,1:-1:2]

array([2, 4, 6])

In [33]:
#Change a value
a[1,5]=20

In [34]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  1, 20, 14]])

In [38]:
#change whole column
a[:,2]=5

In [39]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11,  1, 20, 14]])

In [40]:
a[:,2]=[1,2]

In [41]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11,  1, 20, 14]])

In [46]:
#3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
#Get specific element - work outside in [block,row,element]
b[0,1,1]

4

In [51]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
#replace - must have same indexing
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [56]:
#Initialising diff arrays


In [59]:
#All 0s matrix - any dimention
np.zeros((2,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
#all 1s matrix, can specify data type
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
#any other nr - (dim,val)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [63]:
#any other number (full_like) - take a shape that's already build and pass in to make array thats the same size
#if just use full then have to do a.shape
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [64]:
#matrix of random decimals
np.random.rand(4,2)

array([[0.25746331, 0.42823824],
       [0.27248344, 0.21917427],
       [0.4088515 , 0.30097801],
       [0.46253069, 0.97249454]])

In [65]:
#if want to pass in shape from other matrix
np.random.random_sample(a.shape)

array([[0.80951987, 0.98142036, 0.73203188, 0.02777987, 0.71080113,
        0.54487358, 0.35874446],
       [0.69644494, 0.90266803, 0.37263233, 0.77916333, 0.70097166,
        0.29601885, 0.57048476]])

In [70]:
#random ints - -4 and 7 is the range
np.random.randint(-4,7, size=(3,3))

array([[ 4, -2, -1],
       [ 0, -2,  4],
       [ 3,  4, -1]])

In [71]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [88]:
#initialize array problem

In [85]:
output = np.ones((5,5))
z=np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
#copy an array
a = np.array([1,2,3])
b = a.copy()
b[0]=100

array([100,   2,   3])

In [92]:
#maths

In [106]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [107]:
a + 2

array([3, 4, 5, 6])

In [108]:
a -2 

array([-1,  0,  1,  2])

In [109]:
a * 2

array([2, 4, 6, 8])

In [110]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [111]:
b = np.array([1,0,1,0])

In [112]:
a + b

array([2, 2, 4, 4])

In [113]:
a ** 2

array([ 1,  4,  9, 16])

In [115]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [116]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])